# Generated by Django 3.2.8 on 2021-10-30 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_comment'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.ImageField(default='default.jpg', upload_to='profile_img'),
        ),
        migrations.AddField(
            model_name='profile',
            name='posts',
            field=models.ManyToManyField(to='articles.Post'),
        ),
    ]
