# Generated by Django 3.2.8 on 2021-11-06 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='parent',
        ),
    ]
